# docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - python-service

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python-service:/app
    environment:
      - FLASK_ENV=development

#  db:
#    image: postgres:14-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=pdfuser
#      - POSTGRES_PASSWORD=pdfpassword
#      - POSTGRES_DB=pdfeditor
#    volumes:
#      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: