services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=/api
      - VITE_PYTHON_API_URL=/python-api
    depends_on:
      - backend
      - python-service
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Make sure the swagger.json file is properly mounted
      - ./backend/swagger.json:/app/swagger.json
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=pdfeditor
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET=your-super-secret-key-change-this
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=adminpassword123
    depends_on:
      db:
        condition: service_healthy
      python-service:
        condition: service_started
    restart: on-failure:5

  python-service:
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./python-service:/app
      - ./uploads:/app/uploads
      # Make sure the swagger.json file is properly mounted
      - ./python-service/swagger.json:/app/swagger.json
    environment:
      - FLASK_ENV=development
      - BACKEND_URL=http://backend:3000/api
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_DATABASE: "pdfeditor"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    restart: unless-stopped

volumes:
  dbdata: